/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jia Bangar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        ram = new javax.swing.JTextField();
        rom = new javax.swing.JTextField();
        processor = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nprice = new javax.swing.JTextField();
        oprice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        condition = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        brand1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,0
        ));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255,190));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 30));

        jLabel17.setFont(new java.awt.Font("Engravers MT", 1, 10)); // NOI18N
        jLabel17.setText("Search");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 440, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setAutoCreateRowSorter(true);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Brand", "Model", "Quantity", "IMEI code", "Condition", "RAM", "ROM", "Processor", "Orignal Price", "New Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 840, 530));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel3.setText("Stock");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 60, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 880, 590));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,150
        ));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 10, 340));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel2.setText("Model");
        jLabel2.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, 24));

        jLabel4.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel4.setText("category");
        jLabel4.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, 24));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel6.setText("ORIGNAL PRICE");
        jLabel6.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 160, 24));

        jLabel7.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel7.setText("ROM");
        jLabel7.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, 24));

        jLabel8.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel8.setText("PROCESSOR");
        jLabel8.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 24));

        jLabel9.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel9.setText("CONDITION");
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, 24));

        jLabel10.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel10.setText("rAM");
        jLabel10.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 24));

        jLabel11.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel11.setText("QUANTITY");
        jLabel11.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 24));

        model.setText("iphone x");
        model.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, 24));

        ram.setText("3gb");
        ram.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, 24));

        rom.setText("256gb");
        rom.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(rom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, 24));

        processor.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(processor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 150, 24));

        quantity.setText("22");
        quantity.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 150, 24));

        brand.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, 24));

        jLabel12.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel12.setText("NEW PRICE");
        jLabel12.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 160, 24));

        nprice.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(nprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 150, 24));

        oprice.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(oprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 150, 24));

        jLabel13.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel13.setText("Product Details");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 210, 33));

        save.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 110, 41));

        condition.setEditable(true);
        condition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        condition.setPreferredSize(new java.awt.Dimension(25, 25));
        condition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionActionPerformed(evt);
            }
        });
        jPanel2.add(condition, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, 24));

        jLabel15.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel15.setText("Brand");
        jLabel15.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 160, 24));

        brand1.setText("apple");
        brand1.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel2.add(brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, 24));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 410, 490));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255,150));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jButton1.setText("Sell");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 35));

        jButton2.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jButton2.setText("Record");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 90, 35));

        jButton3.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jButton3.setText("Profit/Loss");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 130, 35));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 440, 90));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255,150));

        jLabel5.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel5.setText("Add Product in Stock");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 50));

        jLabel16.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 26)); // NOI18N
        jLabel16.setText("SYSTEM MANAGEMENT");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel16)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 430, 50));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 880, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 430, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 10, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\19114077_6079758.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    /*  String model1=model.getText();
       String brand1=brand.getText();
       int quantity1=Integer.parseInt(quantity.getText());
       String condition1= (String) condition.getSelectedItem();
       int ram1=Integer.parseInt(ram.getText());       
       int rom1=Integer.parseInt(rom.getText());
       String processor1=processor.getText();
       int oprice1=Integer.parseInt(oprice.getText());
       int nprice1=Integer.parseInt(nprice.getText());
       
       
       try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile_shop","root","");
           PreparedStatement ps = con.prepareStatement("insert into stock values (NULL,?,?,?,?,?,?,?,?,?)");
           ps.setString(1, brand1);
           ps.setString(2, model1);
           ps.setInt(   3, quantity1);
           ps.setString(4, condition1);
           ps.setInt(5, ram1);
           ps.setInt(6, rom1);
           ps.setString(7, brand1);
           ps.setInt(8, oprice1);
           ps.setInt(9, nprice1);
           
           int f=ps.executeUpdate();
           if(f>0){
           JOptionPane.showMessageDialog(null,"Stock Saved.");
           }
           else{
               JOptionPane.showMessageDialog(null,"Not Saved. ");
           }
       }
       catch(Exception e){
           System.out.println("Error"+e);
       }
        try{
            Class.forName("com.mysql.jdbc.Driver");
           Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile_shop","root","");
           PreparedStatement ps = con.prepareStatement("query");
           ResultSet rs= ps.executeQuery("select * from stock");
           DefaultTableModel model = (DefaultTableModel) table.getModel();
           while(rs.next()){
         //  table.setModel(DbUtils.resultSetToTableModel(rs));
           model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)
           ,rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)
           ,rs.getString(10),rs.getString(11)
           });
           }
        }
        catch(Exception e){
            System.out.println("error"+e);
        }*/
        /* if (((!model.getText().equals(""))||(!brand.getText().equals(""))&&
            (!quantity.getText().equals(""))&&(imei.getText().equals("")&&condition.getText().equals(""))&&
            (ram.getText().equals(""))&&(rom.getText().equals(""))&&(processor.getText().equals(""))&&
            (oprice.getText().equals(""))&&(nprice.getText().equals(""))))
    {
        JOptionPane.showMessageDialog(null, "Plese put values");
        }*/
       /* if((!(model.getText().equals("")))&&(!(brand.getText().equals("")))&&
            (!(quantity.getText().equals("")))&&(!(condition.getText().equals("")))&&
            (!(ram.getText().equals("")))&&(!(rom.getText().equals("")))&&(!(processor.getText().equals("")))&&
            (!(oprice.getText().equals("")))&&(!(nprice.getText().equals(""))))
        {
          NewJFrame1.AddRowToJTable(new Object[] {
                model.getText(),brand.getText(),quantity.getText(),
                ram.getText(),rom.getText(),processor.getText(),oprice.getText(),nprice.getText(),
            });}
            else{
                JOptionPane.showMessageDialog(null, "Plese put values");
            }*/
    }//GEN-LAST:event_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void conditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conditionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand;
    private javax.swing.JTextField brand1;
    private javax.swing.JComboBox<String> condition;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField model;
    private javax.swing.JTextField nprice;
    private javax.swing.JTextField oprice;
    private javax.swing.JTextField processor;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField ram;
    private javax.swing.JTextField rom;
    private javax.swing.JButton save;
    private static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
