/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ms;

/**
 *
 * @author Jia Bangar
 */
public class sell extends javax.swing.JFrame {

    /**
     * Creates new form sell
     */
    public sell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nprice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        condition = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        condition1 = new javax.swing.JComboBox<>();
        condition2 = new javax.swing.JComboBox<>();
        condition3 = new javax.swing.JComboBox<>();
        condition4 = new javax.swing.JComboBox<>();
        condition5 = new javax.swing.JComboBox<>();
        condition6 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        condition8 = new javax.swing.JComboBox<>();
        save1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        phoneno1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        nprice1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,210));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 321, -1, -1));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel2.setText("Model");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 125, 26));

        jLabel4.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel4.setText("Brand");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 125, 26));

        jLabel7.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel7.setText("ROM");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 125, 26));

        jLabel8.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel8.setText("PROCESSOR");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 125, 26));

        jLabel9.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel9.setText("CONDITION");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 125, 26));

        jLabel10.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel10.setText("rAM");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 125, 26));

        jLabel11.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel11.setText("QUANTITY");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 125, 26));

        jLabel12.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel12.setText("NEW PRICE");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 116, 26));

        nprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npriceActionPerformed(evt);
            }
        });
        jPanel2.add(nprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 130, -1));

        jLabel13.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel13.setText("Product Details");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 210, 33));

        save.setBackground(new java.awt.Color(204, 255, 204));
        save.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        save.setText("Cancel");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 110, 41));

        condition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 26));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel5.setText("Full name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 125, 26));

        jLabel14.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel14.setText("Total Price");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 140, 26));

        jLabel15.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel15.setText("Customer Details");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 210, 33));
        jPanel2.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 280, 26));
        jPanel2.add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 130, 30));

        condition1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 26));

        condition2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, 26));

        condition3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, 26));

        condition4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 130, 26));

        condition5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, 26));

        condition6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 130, 26));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel6.setText("ORIGNAL PRICE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 26));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 590, 20));

        jLabel16.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel16.setText("category");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 125, 26));

        condition8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Old", " " }));
        jPanel2.add(condition8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, 26));

        save1.setBackground(new java.awt.Color(204, 255, 204));
        save1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        save1.setText("Save");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel2.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 110, 41));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 20, 390));

        jLabel17.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jLabel17.setText("phone no.");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 125, 26));
        jPanel2.add(phoneno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 280, 26));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 280, 30));

        nprice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nprice1ActionPerformed(evt);
            }
        });
        jPanel2.add(nprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
      /*  String model1=model.getText();
        String brand1=brand.getText();
        int quantity1=Integer.parseInt(quantity.getText());
        String condition1= (String) condition.getSelectedItem();
        int ram1=Integer.parseInt(ram.getText());
        int rom1=Integer.parseInt(rom.getText());
        String processor1=processor.getText();
        int oprice1=Integer.parseInt(oprice.getText());
        int nprice1=Integer.parseInt(nprice.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile_shop","root","");
            PreparedStatement ps = con.prepareStatement("insert into stock values (NULL,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, brand1);
            ps.setString(2, model1);
            ps.setInt(   3, quantity1);
            ps.setString(4, condition1);
            ps.setInt(5, ram1);
            ps.setInt(6, rom1);
            ps.setString(7, brand1);
            ps.setInt(8, oprice1);
            ps.setInt(9, nprice1);

            int f=ps.executeUpdate();
            if(f>0){
                JOptionPane.showMessageDialog(null,"Stock Saved.");
            }
            else{
                JOptionPane.showMessageDialog(null,"Not Saved. ");
            }
        }
        catch(Exception e){
            System.out.println("Error"+e);
        }

        /* if (((!model.getText().equals(""))||(!brand.getText().equals(""))&&
            (!quantity.getText().equals(""))&&(imei.getText().equals("")&&condition.getText().equals(""))&&
            (ram.getText().equals(""))&&(rom.getText().equals(""))&&(processor.getText().equals(""))&&
            (oprice.getText().equals(""))&&(nprice.getText().equals(""))))
    {
        JOptionPane.showMessageDialog(null, "Plese put values");
        }*/
        /* if((!(model.getText().equals("")))&&(!(brand.getText().equals("")))&&
            (!(quantity.getText().equals("")))&&(!(condition.getText().equals("")))&&
            (!(ram.getText().equals("")))&&(!(rom.getText().equals("")))&&(!(processor.getText().equals("")))&&
            (!(oprice.getText().equals("")))&&(!(nprice.getText().equals(""))))
        {
            NewJFrame1.AddRowToJTable(new Object[] {
                model.getText(),brand.getText(),quantity.getText(),
                ram.getText(),rom.getText(),processor.getText(),oprice.getText(),nprice.getText(),
            });}
            else{
                JOptionPane.showMessageDialog(null, "Plese put values");
            }*/
    }//GEN-LAST:event_saveActionPerformed

    private void npriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npriceActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save1ActionPerformed

    private void nprice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nprice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nprice1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cname;
    private javax.swing.JComboBox<String> condition;
    private javax.swing.JComboBox<String> condition1;
    private javax.swing.JComboBox<String> condition2;
    private javax.swing.JComboBox<String> condition3;
    private javax.swing.JComboBox<String> condition4;
    private javax.swing.JComboBox<String> condition5;
    private javax.swing.JComboBox<String> condition6;
    private javax.swing.JComboBox<String> condition8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nprice;
    private javax.swing.JTextField nprice1;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTextField phoneno1;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    // End of variables declaration//GEN-END:variables
}
